-- ============================================================
-- KPI Dashboard — Identity Columns Generation Type Fix
-- Run this in Supabase SQL Editor to allow client-supplied IDs.
-- Safe to re-run (idempotent).
-- ============================================================

ALTER TABLE public.faculties ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.departments ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.professors ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.plans ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.achievements ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.projects ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.thesis_defenses ALTER COLUMN id SET GENERATED BY DEFAULT;

-- Verify change
SELECT 
  table_schema, 
  table_name, 
  column_name, 
  is_identity, 
  identity_generation
FROM information_schema.columns
WHERE table_schema = 'public' 
  AND column_name = 'id'
  AND table_name IN ('faculties', 'departments', 'professors', 'plans', 'achievements', 'projects', 'thesis_defenses');
