-- ============================================================
-- KPI Dashboard — Supabase Schema (idempotent, run any time)
-- ============================================================

-- ─── Tables ──────────────────────────────────────────────────

create table if not exists public.app_state (
  id         text        primary key,
  data       jsonb       not null check (jsonb_typeof(data) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint app_state_id_not_blank check (btrim(id) <> '')
);

create table if not exists public.faculties (
  id         bigint generated by default as identity primary key,
  name       text        not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.departments (
  id         bigint generated by default as identity primary key,
  faculty_id bigint      not null references public.faculties(id) on delete cascade,
  name       text        not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint departments_name_unique_per_faculty unique (faculty_id, name)
);

create table if not exists public.professors (
  id              bigint generated by default as identity primary key,
  department_id   bigint      not null references public.departments(id) on delete cascade,
  first_name      text        not null,
  last_name       text        not null,
  patronymic      text,
  birth_date      date,
  gender          text        not null check (gender in ('erkak', 'ayol')),
  degree          text,
  title           text,
  position        text,
  employment_type text,
  phone           text,
  staff_unit      numeric(4,2) not null default 0,
  created_at      timestamptz  not null default now(),
  updated_at      timestamptz  not null default now()
);

create table if not exists public.plans (
  id           bigint generated by default as identity primary key,
  professor_id bigint  not null references public.professors(id) on delete cascade,
  year         integer not null,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  constraint plans_unique_per_professor_year unique (professor_id, year)
);

create table if not exists public.plan_items (
  plan_id    bigint        not null references public.plans(id) on delete cascade,
  type       text          not null,
  sub_type   text          not null,
  count      numeric(12,2) not null default 0,
  created_at timestamptz   not null default now(),
  primary key (plan_id, type, sub_type)
);

create table if not exists public.achievements (
  id           bigint generated by default as identity primary key,
  professor_id bigint        not null references public.professors(id) on delete cascade,
  year         integer       not null,
  quarter      integer       not null check (quarter between 1 and 4),
  type         text          not null,
  sub_type     text          not null,
  count        numeric(12,2) not null default 0,
  created_at   timestamptz   not null default now(),
  updated_at   timestamptz   not null default now(),
  constraint achievements_unique_per_professor_period unique (professor_id, year, quarter, type, sub_type)
);

create table if not exists public.projects (
  id              bigint generated by default as identity primary key,
  department_id   bigint         not null references public.departments(id) on delete cascade,
  faculty_id      bigint         not null references public.faculties(id) on delete cascade,
  name            text           not null,
  type            text           not null,
  direction       text           not null,
  leader_name     text           not null,
  leader_position text           not null,
  total_funding   numeric(18,2)  not null default 0,
  duration        integer        not null default 1,
  created_at      timestamptz    not null default now(),
  updated_at      timestamptz    not null default now()
);

create table if not exists public.thesis_defenses (
  id                  bigint generated by default as identity primary key,
  department_id       bigint      not null references public.departments(id) on delete cascade,
  faculty_id          bigint      not null references public.faculties(id) on delete cascade,
  last_name           text        not null,
  first_name          text        not null,
  patronymic          text,
  specialty           text,
  type                text        not null,
  field_of_science    text,
  thesis_topic        text        not null,
  supervisor          text,
  defense_organization text,
  council_number      text,
  defense_date        date,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create table if not exists public.app_users (
  id         uuid  primary key references auth.users(id) on delete cascade,
  email      text  not null unique,
  role       text  not null check (role in ('admin', 'superadmin', 'guest')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ─── Indexes ─────────────────────────────────────────────────

create index if not exists idx_app_state_updated_at      on public.app_state      (updated_at desc);
create index if not exists idx_departments_faculty_id    on public.departments    (faculty_id);
create index if not exists idx_professors_department_id  on public.professors     (department_id);
create index if not exists idx_plans_professor_year      on public.plans          (professor_id, year);
create index if not exists idx_achievements_professor    on public.achievements   (professor_id, year);
create index if not exists idx_projects_department_id    on public.projects       (department_id);
create index if not exists idx_thesis_defenses_dept      on public.thesis_defenses(department_id);

-- ─── Trigger function ────────────────────────────────────────

create or replace function public.trigger_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- ─── Triggers (drop-and-recreate for idempotency) ────────────

drop trigger if exists app_state_set_updated_at      on public.app_state;
drop trigger if exists faculties_set_updated_at       on public.faculties;
drop trigger if exists departments_set_updated_at     on public.departments;
drop trigger if exists professors_set_updated_at      on public.professors;
drop trigger if exists plans_set_updated_at           on public.plans;
drop trigger if exists achievements_set_updated_at    on public.achievements;
drop trigger if exists projects_set_updated_at        on public.projects;
drop trigger if exists thesis_defenses_set_updated_at on public.thesis_defenses;
drop trigger if exists app_users_set_updated_at       on public.app_users;

create trigger app_state_set_updated_at
  before insert or update on public.app_state
  for each row execute function public.trigger_set_updated_at();

create trigger faculties_set_updated_at
  before insert or update on public.faculties
  for each row execute function public.trigger_set_updated_at();

create trigger departments_set_updated_at
  before insert or update on public.departments
  for each row execute function public.trigger_set_updated_at();

create trigger professors_set_updated_at
  before insert or update on public.professors
  for each row execute function public.trigger_set_updated_at();

create trigger plans_set_updated_at
  before insert or update on public.plans
  for each row execute function public.trigger_set_updated_at();

create trigger achievements_set_updated_at
  before insert or update on public.achievements
  for each row execute function public.trigger_set_updated_at();

create trigger projects_set_updated_at
  before insert or update on public.projects
  for each row execute function public.trigger_set_updated_at();

create trigger thesis_defenses_set_updated_at
  before insert or update on public.thesis_defenses
  for each row execute function public.trigger_set_updated_at();

create trigger app_users_set_updated_at
  before insert or update on public.app_users
  for each row execute function public.trigger_set_updated_at();

-- ─── is_app_admin() ──────────────────────────────────────────
-- Checks (in order):
--   1. user_metadata.role = admin/superadmin
--   2. app_metadata.role  = admin/superadmin
--   3. email in hardcoded admin list
--   4. app_users table has role admin/superadmin (most reliable)

create or replace function public.is_app_admin()
returns boolean
language sql
stable
security definer
set search_path = ''            -- prevents search_path injection
as $$
  select coalesce(
    -- Check 1: user_metadata.role (set in Supabase Dashboard → Auth → Users)
    lower(coalesce(auth.jwt() -> 'user_metadata' ->> 'role', ''))
      = any (array['admin', 'superadmin'])
    -- Check 2: app_metadata.role (set via service-role API or SQL)
    or lower(coalesce(auth.jwt() -> 'app_metadata' ->> 'role', ''))
      = any (array['admin', 'superadmin'])
    -- Check 3: JWT email whitelist (always reliable — no table lookup)
    or lower(coalesce(auth.jwt() ->> 'email', ''))
      = any (array['suhrobiddinnuraliyev04@gmail.com'])
    -- Check 4: app_users table (SECURITY DEFINER bypasses RLS here — no recursion)
    or exists (
      select 1
      from   public.app_users
      where  id   = auth.uid()
        and  role in ('admin', 'superadmin')
    ),
    false
  );
$$;

-- ─── Enable RLS ──────────────────────────────────────────────

alter table public.app_state      enable row level security;
alter table public.faculties       enable row level security;
alter table public.departments     enable row level security;
alter table public.professors      enable row level security;
alter table public.plans           enable row level security;
alter table public.plan_items      enable row level security;
alter table public.achievements    enable row level security;
alter table public.projects        enable row level security;
alter table public.thesis_defenses enable row level security;
alter table public.app_users       enable row level security;

-- ─── RLS Policies (IF NOT EXISTS for idempotency) ────────────

-- app_state: public read
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='app_state' and policyname='anon_read_app_state') then
    create policy anon_read_app_state on public.app_state for select to anon using (true);
  end if;
end $$;

-- app_state: admin write
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='app_state' and policyname='admin_insert_app_state') then
    create policy admin_insert_app_state on public.app_state for insert to authenticated with check (public.is_app_admin());
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='app_state' and policyname='admin_update_app_state') then
    create policy admin_update_app_state on public.app_state for update to authenticated using (public.is_app_admin()) with check (public.is_app_admin());
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='app_state' and policyname='admin_delete_app_state') then
    create policy admin_delete_app_state on public.app_state for delete to authenticated using (public.is_app_admin());
  end if;
end $$;

-- faculties: public read, admin write
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='faculties' and policyname='anon_read_faculties') then
    create policy anon_read_faculties on public.faculties for select to anon using (true);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='faculties' and policyname='admin_manage_faculties') then
    create policy admin_manage_faculties on public.faculties for all to authenticated using (public.is_app_admin()) with check (public.is_app_admin());
  end if;
end $$;

-- departments: public read, admin write
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='departments' and policyname='anon_read_departments') then
    create policy anon_read_departments on public.departments for select to anon using (true);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='departments' and policyname='admin_manage_departments') then
    create policy admin_manage_departments on public.departments for all to authenticated using (public.is_app_admin()) with check (public.is_app_admin());
  end if;
end $$;

-- professors: public read, admin write
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='professors' and policyname='anon_read_professors') then
    create policy anon_read_professors on public.professors for select to anon using (true);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='professors' and policyname='admin_manage_professors') then
    create policy admin_manage_professors on public.professors for all to authenticated using (public.is_app_admin()) with check (public.is_app_admin());
  end if;
end $$;

-- plans: public read, admin write
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='plans' and policyname='anon_read_plans') then
    create policy anon_read_plans on public.plans for select to anon using (true);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='plans' and policyname='admin_manage_plans') then
    create policy admin_manage_plans on public.plans for all to authenticated using (public.is_app_admin()) with check (public.is_app_admin());
  end if;
end $$;

-- plan_items: public read, admin write
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='plan_items' and policyname='anon_read_plan_items') then
    create policy anon_read_plan_items on public.plan_items for select to anon using (true);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='plan_items' and policyname='admin_manage_plan_items') then
    create policy admin_manage_plan_items on public.plan_items for all to authenticated using (public.is_app_admin()) with check (public.is_app_admin());
  end if;
end $$;

-- achievements: public read, admin write
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='achievements' and policyname='anon_read_achievements') then
    create policy anon_read_achievements on public.achievements for select to anon using (true);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='achievements' and policyname='admin_manage_achievements') then
    create policy admin_manage_achievements on public.achievements for all to authenticated using (public.is_app_admin()) with check (public.is_app_admin());
  end if;
end $$;

-- projects: public read, admin write
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='projects' and policyname='anon_read_projects') then
    create policy anon_read_projects on public.projects for select to anon using (true);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='projects' and policyname='admin_manage_projects') then
    create policy admin_manage_projects on public.projects for all to authenticated using (public.is_app_admin()) with check (public.is_app_admin());
  end if;
end $$;

-- thesis_defenses: public read, admin write
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='thesis_defenses' and policyname='anon_read_thesis_defenses') then
    create policy anon_read_thesis_defenses on public.thesis_defenses for select to anon using (true);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='thesis_defenses' and policyname='admin_manage_thesis_defenses') then
    create policy admin_manage_thesis_defenses on public.thesis_defenses for all to authenticated using (public.is_app_admin()) with check (public.is_app_admin());
  end if;
end $$;

-- app_users: authenticated read, admin write
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='app_users' and policyname='auth_read_app_users') then
    create policy auth_read_app_users on public.app_users for select to authenticated using (true);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='app_users' and policyname='admin_manage_app_users') then
    create policy admin_manage_app_users on public.app_users for all to authenticated using (public.is_app_admin()) with check (public.is_app_admin());
  end if;
end $$;
