-- Migration: change GENERATED ALWAYS → GENERATED BY DEFAULT
-- Bu o'zgartirish localStorage'dan ma'lumot import qilish uchun zarur
-- Supabase Dashboard > SQL Editor da ishga tushiring

ALTER TABLE public.faculties
  ALTER COLUMN id SET GENERATED BY DEFAULT;

ALTER TABLE public.departments
  ALTER COLUMN id SET GENERATED BY DEFAULT;

ALTER TABLE public.professors
  ALTER COLUMN id SET GENERATED BY DEFAULT;

ALTER TABLE public.plans
  ALTER COLUMN id SET GENERATED BY DEFAULT;

ALTER TABLE public.achievements
  ALTER COLUMN id SET GENERATED BY DEFAULT;

ALTER TABLE public.projects
  ALTER COLUMN id SET GENERATED BY DEFAULT;

ALTER TABLE public.thesis_defenses
  ALTER COLUMN id SET GENERATED BY DEFAULT;

-- Sequencelarni mavjud max ID dan katta qilib qayta o'rnatish
-- (agar allaqachon ma'lumot bo'lsa)
SELECT setval(pg_get_serial_sequence('public.faculties','id'),    COALESCE(MAX(id),0)+1, false) FROM public.faculties;
SELECT setval(pg_get_serial_sequence('public.departments','id'),  COALESCE(MAX(id),0)+1, false) FROM public.departments;
SELECT setval(pg_get_serial_sequence('public.professors','id'),   COALESCE(MAX(id),0)+1, false) FROM public.professors;
SELECT setval(pg_get_serial_sequence('public.plans','id'),        COALESCE(MAX(id),0)+1, false) FROM public.plans;
SELECT setval(pg_get_serial_sequence('public.achievements','id'), COALESCE(MAX(id),0)+1, false) FROM public.achievements;
SELECT setval(pg_get_serial_sequence('public.projects','id'),     COALESCE(MAX(id),0)+1, false) FROM public.projects;
SELECT setval(pg_get_serial_sequence('public.thesis_defenses','id'), COALESCE(MAX(id),0)+1, false) FROM public.thesis_defenses;
